# Generated by Django 3.2 on 2022-06-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barber',
            fields=[
                ('barber_code', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('limit', models.IntegerField()),
                ('earned_money', models.BigIntegerField()),
            ],
        ),
    ]
