# Generated by Django 3.2 on 2022-06-30 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='number_of_hair_cut',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
