# Generated by Django 3.2 on 2022-06-30 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0002_barber_number_of_hair_cut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barber',
            name='earned_money',
        ),
    ]
