# Generated by Django 3.2 on 2022-06-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0004_auto_20220630_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='barberdata',
            name='date',
            field=models.DateField(),
            preserve_default=False,
        ),
    ]
