# Generated by Django 3.2 on 2022-07-01 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personnels', '0001_initial'),
        ('barbers', '0005_barberdata_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barberdata',
            options={'ordering': ['-date']},
        ),
        migrations.CreateModel(
            name='BarberHairCut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('barber_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barbers.barber')),
                ('personnel_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnels.personnel')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
