# Generated by Django 3.2 on 2022-07-01 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0006_auto_20220701_1835'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BarberData',
        ),
    ]
